spring:
  application:
    name: backend
  datasource:
    url: jdbc:h2:file:./data/nhangsi;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
      path: /h2-console
