"use client";
import{useState}from"react";import{usePathname,useRouter}from"next/navigation";
type Poem={id:string;word:string;lines:string[];user:string;rating:number;ratings:number;comments:number;time:string};
const poems:Poem[]=[
{id:"1",word:"대학교",lines:["대충 살자고 했는데","학점은 왜","교수님 마음대로인가요"],user:"복학생A",rating:4.8,ratings:231,comments:18,time:"14분 전"},
{id:"2",word:"고양이",lines:["고민은 잠시 내려놓고","양손 가득 츄르를 들면","이제 내가 집사다"],user:"냥냥펀치",rating:4.6,ratings:98,comments:12,time:"32분 전"},
{id:"3",word:"퇴근",lines:["퇴근한다고 말은 했지만","근처에도 못 갔다"],user:"퇴근하고싶다",rating:4.9,ratings:412,comments:34,time:"1시간 전"},
{id:"4",word:"감자",lines:["감동적인 하루의 끝엔","자꾸만 네가 생각나, 감자전"],user:"감자전문가",rating:4.3,ratings:67,comments:7,time:"2시간 전"},
{id:"5",word:"알바",lines:["알람보다 먼저 눈을 떴다","바로 오늘이 월급날이라서"],user:"코딩노예",rating:4.7,ratings:144,comments:21,time:"3시간 전"}];
const randomWords=["고양이","아메리카노","월요일","지하철","복숭아","대학교"];
function Logo(){return <a href="/" className="logo"><i>N</i>행시</a>}
function Header(){return <><header><div><Logo/><nav><a href="/">홈</a><a href="/poems">둘러보기</a><a href="/write">글쓰기</a><a href="/me">내 활동</a></nav><a className="profile" href="/users/me"><b>코</b>코딩노예</a></div></header><nav className="mobile"><a href="/">⌂<span>홈</span></a><a href="/poems">⌕<span>탐색</span></a><a className="write" href="/write">＋<span>쓰기</span></a><a href="/me">○<span>내 활동</span></a></nav></>}
function Btn({children,kind="primary",onClick,disabled=false}:{children:React.ReactNode;kind?:string;onClick?:()=>void;disabled?:boolean}){return <button className={"btn "+kind} onClick={onClick} disabled={disabled}>{children}</button>}
function Tabs({items,active,set}:{items:string[];active:string;set:(x:string)=>void}){return <div className="tabs">{items.map(x=><button key={x} className={active===x?"active":""} onClick={()=>set(x)}>{x}</button>)}</div>}
function Lines({p}:{p:Pick<Poem,"word"|"lines">}){return <div className="lines">{[...p.word].map((c,i)=><p key={i}><b>{c}</b><span>{p.lines[i]}</span></p>)}</div>}
function Card({p,rank}:{p:Poem;rank?:number}){return <article className="card"><a href={"/poems/"+p.id}><div className="cardtop">{rank&&<em>{rank}</em>}<div><small>제시어</small><h3>{p.word}</h3></div><button aria-label="더보기">•••</button></div><Lines p={p}/><div className="by"><b>{p.user[0]}</b><span>@{p.user} · {p.time}</span></div><div className="meta"><strong>★ {p.rating}</strong><span>평가 {p.ratings}</span><span>댓글 {p.comments}</span></div></a></article>}
function Title({children,sub}:{children:React.ReactNode;sub?:string}){return <div className="title"><h2>{children}</h2>{sub&&<p>{sub}</p>}</div>}
function Ad(){return <div className="ad"><small>ADVERTISEMENT</small><span>콘텐츠 사이의 여유로운 광고 영역</span></div>}
function PageHead({label,title,desc}:{label:string;title:string;desc:string}){return <div className="pagehead"><small>{label}</small><h1>{title}</h1><p>{desc}</p></div>}
function Toast({text}:{text:string}){return text?<div className="toast">✓ {text}</div>:null}
function Home(){const[t,setT]=useState("인기");const list=t==="최신"?[...poems].reverse():t==="랜덤"?[poems[2],poems[0],poems[4]]:poems;return <><section className="hero"><div><small>오늘의 단어 · 8월 15일</small><h1>“알바”</h1><p><b>1,284명</b>이 오늘의 단어로 웃음을 만들었어요</p><div><a className="btn primary" href="/write/custom?word=알바">N행시 쓰기 →</a><a className="btn secondary" href="/write/random">랜덤 단어 받기</a></div></div><aside><small>오늘의 1위</small><p><b>알</b> 알람보다 먼저 눈을 떴다</p><p><b>바</b> 바로 오늘이 월급날이라서</p></aside></section><div className="sectionrow"><Title sub="짧게 읽고, 마음껏 평가해보세요">지금 웃긴 N행시</Title><a href="/random">하나씩 보기 →</a></div><Tabs items={["인기","최신","랜덤"]} active={t} set={setT}/><div className="feed">{list.map((p,i)=><div key={p.id}><Card p={p}/>{i===2&&<Ad/>}</div>)}</div></>}
function Write(){const router=useRouter();const path=usePathname();const query=typeof window!=="undefined"?new URLSearchParams(location.search).get("word")||"":"";const[mode,setMode]=useState(path.includes("random")?"랜덤 단어":"직접 입력");const[word,setWord]=useState(query||(path.includes("random")?"고양이":""));const[start,setStart]=useState(!!query||path.includes("random"));const[lines,setLines]=useState<string[]>([...word].map(()=>""));const[toast,setToast]=useState("");const begin=(w=word)=>{if(w.length<2||w.length>6){setToast("단어는 2~6글자로 입력해주세요");return}setWord(w);setLines([...w].map(()=>""));setStart(true)};const random=()=>begin(randomWords[Math.floor(Math.random()*randomWords.length)]);return <><PageHead label="CREATE" title="한 글자씩 이어볼까요?" desc="완벽하지 않아도 괜찮아요. 짧고 솔직할수록 더 재밌으니까."/><Tabs items={["랜덤 단어","직접 입력"]} active={mode} set={v=>{setMode(v);setStart(false);setWord("");if(v==="랜덤 단어")setTimeout(random)}}/><section className="writecard">{!start?<div className="wordinput"><label>제시어</label><div><input value={word} onChange={e=>setWord(e.target.value.replace(/\s/g,"").slice(0,6))} placeholder="2~6글자 단어를 입력하세요"/><Btn onClick={()=>begin()}>N행시 시작</Btn></div><small>{word.length} / 6 · 한글 단어를 추천해요</small></div>:<><div className="chosen"><small>당신의 단어</small><h2>{word}</h2>{mode==="랜덤 단어"&&<Btn kind="secondary" onClick={random}>↻ 다른 단어</Btn>}</div><div className="inputs">{[...word].map((c,i)=><label key={i}><b>{c}</b><span><input value={lines[i]} maxLength={80} onChange={e=>setLines(a=>a.map((v,n)=>n===i?e.target.value:v))} placeholder={"“"+c+"”로 시작하는 문장을 입력하세요"}/><small>{lines[i].length} / 80</small></span></label>)}</div></>}</section>{start&&<section className="preview"><small>PREVIEW</small><h2>내 N행시 미리보기</h2><h3>{word}</h3><Lines p={{word,lines:lines.map(x=>x||"문장을 입력해주세요")}}/><div><Btn kind="ghost" onClick={()=>setLines(lines.map(()=>""))}>임시 초기화</Btn><Btn disabled={lines.some(x=>!x.trim())} onClick={()=>{setToast("N행시가 등록되었어요!");setTimeout(()=>router.push("/poems/1"),600)}}>등록하기</Btn></div></section>}<Toast text={toast}/></>}
function Stars({value,set}:{value:number;set:(n:number)=>void}){const[h,setH]=useState(0);return <div className="stars" onMouseLeave={()=>setH(0)}>{[1,2,3,4,5].map(n=><button key={n} aria-label={n+"점"} className={(h||value)>=n?"on":""} onMouseEnter={()=>setH(n)} onFocus={()=>setH(n)} onClick={()=>set(n)}>★</button>)}</div>}
function Detail(){const p=poems.find(x=>x.id===usePathname().split("/").pop());const[rating,setRating]=useState(0);const[text,setText]=useState("");const[list,setList]=useState(["마지막 줄에서 진심이 느껴져요 ㅋㅋ","이번 학기 제 이야기인 줄 알았어요","웃픈데 별점은 5점 드립니다"]);const[modal,setModal]=useState("");const[toast,setToast]=useState("");if(!p)return <Empty error/>;return <><article className="detail"><div className="actions"><button onClick={()=>setModal("share")}>↗ 공유</button><button onClick={()=>setModal("report")}>⚑ 신고</button></div><small>제시어</small><h1>{p.word}</h1><div className="detailby"><b>{p.user[0]}</b><span><strong>{p.user}</strong><small>{p.time}</small></span></div><Lines p={p}/><div className="meta"><strong>★ {p.rating}</strong><span>평가 {p.ratings}</span><span>댓글 {p.comments}</span></div></article><section className="ratingbox"><div><h2>{rating?"평가를 남겼어요":"이 N행시는 몇 점?"}</h2><p>{rating?"내 평가 "+rating+"점 · 언제든 수정할 수 있어요":"평균 "+p.rating+" · "+p.ratings+"명 평가"}</p></div><Stars value={rating} set={n=>{setRating(n);setToast(n+"점으로 평가했어요")}}/></section><Ad/><section className="comments"><Title sub="재미있게 읽었다면 한마디 남겨보세요">댓글 {list.length+15}</Title><div className="commentform"><b>코</b><div><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="댓글을 입력하세요"/><Btn onClick={()=>{if(text.trim()){setList([text,...list]);setText("");setToast("댓글이 등록되었어요")}}}>등록</Btn></div></div>{list.map((x,i)=><div className="comment" key={i}><b>{["감","냥","퇴"][i%3]}</b><div><strong>{["감자전문가","냥냥펀치","퇴근하고싶다"][i%3]}</strong><small>{i+8}분 전 · •••</small><p>{x}</p><button>답글</button></div></div>)}</section>{modal&&<div className="modalback"><div className="modal"><div><h2>{modal==="share"?"공유하기":"신고하기"}</h2><button onClick={()=>setModal("")}>×</button></div>{modal==="share"?<><Btn onClick={()=>{navigator.clipboard?.writeText(location.href);setModal("");setToast("링크를 복사했어요")}}>링크 복사</Btn><Btn kind="secondary">공유하기</Btn></>:<Report done={()=>{setModal("");setToast("신고가 접수되었습니다")}}/>}</div></div>}<Toast text={toast}/></>}
function Report({done}:{done:()=>void}){const[r,setR]=useState("");return <div className="report">{["욕설/비방","혐오 표현","음란성 콘텐츠","도배/스팸","개인정보 노출","기타"].map(x=><label key={x}><input type="radio" name="r" onChange={()=>setR(x)}/>{x}</label>)}{r==="기타"&&<textarea placeholder="신고 사유를 입력해주세요"/>}<Btn disabled={!r} onClick={done}>신고하기</Btn></div>}
function Explore(){const[q,setQ]=useState("");const[sort,setSort]=useState("인기순");const list=poems.filter(p=>p.word.includes(q)||p.lines.some(x=>x.includes(q)));return <><PageHead label="EXPLORE" title="웃음 찾기" desc="단어와 문장 속에서 취향에 맞는 N행시를 발견해보세요."/><div className="search">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="단어 또는 내용 검색"/></div><div className="chips">{["인기순","최신순","별점순","댓글 많은 순"].map(x=><button className={sort===x?"active":""} onClick={()=>setSort(x)} key={x}>{x}</button>)}</div><Title sub={"전체 · "+sort}>{list.length}개의 N행시</Title><div className="feed">{list.map(p=><Card key={p.id} p={p}/>)}</div>{!list.length&&<Empty/>}</>}
function Daily(){return <><section className="daily"><small>오늘의 단어 · 8월 15일</small><h1>알바</h1><p>오늘 <b>1,284명</b>이 참여했어요</p><a className="btn primary" href="/write/custom?word=알바">나도 참여하기</a></section><Title sub="자정까지 순위가 달라질 수 있어요">오늘의 TOP 3</Title><div className="feed">{[poems[4],poems[2],poems[0]].map((p,i)=><Card key={p.id} p={p} rank={i+1}/>)}</div></>}
function Random(){const[i,setI]=useState(0);const[r,setR]=useState(0);return <><PageHead label="RANDOM PLAY" title="하나씩 가볍게" desc={(i+1)+" / "+poems.length}/><article className="randomcard"><small>{poems[i].word}</small><Lines p={poems[i]}/><div className="by"><b>{poems[i].user[0]}</b>@{poems[i].user}</div><Stars value={r} set={setR}/></article><div className="randomnav"><Btn kind="secondary" onClick={()=>{setI((i-1+poems.length)%poems.length);setR(0)}}>← 이전</Btn><span>평가하고 다음 작품으로</span><Btn onClick={()=>{setI((i+1)%poems.length);setR(0)}}>다음 →</Btn></div></>}
function Profile({mine=false}:{mine?:boolean}){const[t,setT]=useState("작성한 N행시");return <><section className="profilepage"><b>{mine?"코":"복"}</b><div><small>PROFILE</small><h1>{mine?"코딩노예":"복학생A"}</h1><p>2025. 3. 12부터 한 글자씩 웃음을 만드는 중</p></div>{mine&&<Btn kind="secondary">프로필 수정</Btn>}</section><div className="stats"><div><b>18</b><span>작성한 N행시</span></div><div><b>4.7</b><span>평균 받은 별점</span></div><div><b>1,204</b><span>총 평가 수</span></div></div><Tabs items={["작성한 N행시","댓글","평가한 글"]} active={t} set={setT}/><div className="feed">{poems.slice(mine?3:0,mine?5:2).map(p=><Card key={p.id} p={p}/>)}</div></>}
function Auth({signup=false}:{signup?:boolean}){return <div className="auth"><section><Logo/><small>{signup?"JOIN US":"WELCOME BACK"}</small><h1>{signup?"같이 웃을 준비됐나요?":"다시 만나서 반가워요"}</h1><p>{signup?"가입하고 첫 N행시를 남겨보세요.":"로그인하고 쓰기, 평가, 댓글을 이어가세요."}</p><form onSubmit={e=>e.preventDefault()}><label>이메일<input type="email" placeholder="hello@example.com"/></label>{signup&&<label>닉네임<input placeholder="멋진 닉네임"/></label>}<label>비밀번호<input type="password" placeholder="8자 이상 입력"/></label><Btn>{signup?"회원가입":"로그인"}</Btn></form><div><a href={signup?"/login":"/signup"}>{signup?"이미 계정이 있어요":"회원가입"}</a><a href="#">비밀번호 찾기</a></div></section></div>}
function Admin(){return <><PageHead label="ADMIN" title="신고 관리" desc="신고된 콘텐츠를 검토하고 처리 상태를 관리합니다."/><div className="table">{[["유형","콘텐츠","신고 사유","상태","관리"],["게시글","대학교 N행시","욕설/비방","검토 중","보기 · 숨김"],["댓글","마지막 줄에서…","도배/스팸","대기","보기 · 숨김"]].map((r,i)=><div className={i?"":"thead"} key={i}>{r.map(x=><span key={x}>{x}</span>)}</div>)}</div></>}
function Empty({error=false}:{error?:boolean}){return <div className="empty"><i>{error?"!":"✦"}</i><h2>{error?"이 N행시는 존재하지 않거나 삭제되었습니다":"찾는 N행시가 없어요"}</h2><p>홈에서 다른 작품을 만나거나 직접 만들어보세요.</p><a className="btn primary" href={error?"/":"/write"}>{error?"홈으로":"N행시 쓰기"}</a></div>}
export default function App(){const path=usePathname();const auth=path==="/login"||path==="/signup";let page:React.ReactNode;if(path==="/")page=<Home/>;else if(path.startsWith("/write"))page=<Write/>;else if(/^\/poems\/./.test(path))page=<Detail/>;else if(path==="/poems")page=<Explore/>;else if(path==="/daily")page=<Daily/>;else if(path==="/random")page=<Random/>;else if(path==="/me")page=<Profile mine/>;else if(path.startsWith("/users/"))page=<Profile mine={path.endsWith("/me")}/>;else if(path==="/login")page=<Auth/>;else if(path==="/signup")page=<Auth signup/>;else if(path==="/admin")page=<Admin/>;else page=<Empty error/>;return <>{!auth&&<Header/>}<main className={auth?"authmain":"main"}>{page}</main></>}